---
apiVersion: v2 # v2 for Helm v3
name: monitoring
version: 1.0.0
dependencies:
  - name: influxdb
    repository: https://influxdata.github.io/helm-charts
    version: 4.12.1 # version: of https://github.com/influxdata/helm-charts/blob/master/charts/influxdb/Chart.yaml
    condition: influxdb.enabled
  - name: telegraf
    repository: https://influxdata.github.io/helm-charts
    version: 1.8.26 # version: of https://github.com/influxdata/helm-charts/blob/master/charts/telegraf/Chart.yaml
    condition: telegraf.enabled
  - name: grafana
    repository: https://grafana.github.io/helm-charts
    version: 6.52.4
    condition: grafana.enabled


    
